#include <u.h>
#include <libc.h>
#include <thread.h>
#include <fcall.h>
#include <9pclient.h>
#include <acme.h>
#include "term.h"

const char *termprog = "win";

#define	STACK	32768

typedef struct Q Q;

Event blank = {
	'M',
	'X',
	0, 0, 0, 0, 0, 1, 1,
	" ",
};

struct Q
{
	QLock	lk;
	int		p;
	int		k;
};

Q	q;

Win *win;

char	*typing;
int	ntypeb;
int	ntyper;
int	ntypebreak;
int	debug;
int	rcfd;
int	cook = 1;
int	password;
int	israw(int);

char *name;

char **prog;
Channel *cwait;
int pid = -1;
int	childdone;
int	outbusy;
ulong	outcount;

int	label(char*, int);
void	error(char*, ...);
void	stdinproc(void*);
void	stdoutproc(void*);
void	type(Event*, int);
void	sende(Event*, int, int);
int	issend(Event*);
void	sendcmd(Event*, int);
void	sendtext(char*, int, int, int);
char	*onestring(int, char**);
int	delete(Event*);
void	deltype(uint, uint);
void	sendbs(int, int);
void	runproc(void*);
void	drainout(void);

void
usage(void)
{
	fprint(2, "usage: win cmd args...\n");
	threadexitsall("usage");
}

/* let stdoutproc finish reading the pty */
void
drainout(void)
{
	ulong last;
	int i, idle;

	idle = 0;
	for(i=0; i<100 && idle<3; i++){
		last = outcount;
		sleep(20);
		if(!outbusy && outcount == last)
			idle++;
		else
			idle = 0;
	}
}

void
waitthread(void *v)
{
	for(;;){
		if(childdone || nbrecvp(cwait) != nil)
			break;
		sleep(20);
	}
	drainout();
	threadexitsall(nil);
}

void
hangupnote(void *a, char *msg)
{
	if(strcmp(msg, "hangup") == 0 && pid != 0){
		postnote(PNGROUP, pid, "hangup");
		noted(NDFLT);
	}
	if(strstr(msg, "child")){
		char buf[128];
		int n;

		n = awaitnohang(buf, sizeof buf-1);
		if(n > 0){
			buf[n] = 0;
			if(atoi(buf) == pid)
				childdone = 1;
		}
		noted(NCONT);
	}
	noted(NDFLT);
}

void
threadmain(int argc, char **argv)
{
	int n;
	char buf[256];
	char buf1[128];
	char *dump;

	dump = onestring(argc, argv);

	ARGBEGIN{
	case 'd':
		debug = 1;
		break;
	case 'n':
		name = EARGF(usage());
		break;
	default:
		usage();
	}ARGEND

	prog = argv;

	if(name == nil){
		if(argc > 0)
			name = argv[0];
		else{
			name = sysname();
			if(name == nil)
				name = "gnot";
		}
	}

	/*
	 * notedisable("sys: write on closed pipe");
	 * not okay to disable the note, because that
	 * gets inherited by the subshell, so that something
	 * as simple as "yes | sed 10q" never exits.
	 * call notifyoff instead.  (is notedisable ever safe?)
	 */
	notifyoff("sys: write on closed pipe");

	noteenable("sys: child");
	notify(hangupnote);

	win = newwin();
	snprint(buf, sizeof buf, "%d", win->id);
	putenv("winid", buf);
	getwd(buf1, sizeof buf1);
	if(!win->fromdump){
		winname(win, "%s/-%s", buf1, name);
		wincmds(win, " Del Look Send ");
		winctl(win, "scratch");
	}
	winctl(win, "dumpdir %s/\n", buf1);
	winctl(win, "dump %s\n", dump);

	winseek(win, "event", 0, 0);
	winseek(win, "data", 0, 0);
	/* resume q.p at end of restored body, not 0 */
	winaddr(win, "$");
	n = winreadaddr(win, nil);
	if(n >= 0)
		q.p = n;

	cwait = threadwaitchan();
	proccreate(waitthread, nil, STACK);
	pid = rcstart(argc, argv, &rcfd, nil);
	if(pid == -1)
		sysfatal("exec failed");

	updatewinsize(25, 80, 0, 0);
	proccreate(stdoutproc, nil, STACK);
	stdinproc(nil);
}

void
error(char *s, ...)
{
	va_list arg;

	if(s){
		va_start(arg, s);
		s = vsmprint(s, arg);
		va_end(arg);
		fprint(2, "win: %s: %r\n", s);
	}
	if(pid != -1)
		postnote(PNGROUP, pid, "hangup");
	threadexitsall(s);
}

char*
onestring(int argc, char **argv)
{
	char *p;
	int i, n;
	static char buf[1024];

	if(argc == 0)
		return "";
	p = buf;
	for(i=0; i<argc; i++){
		n = strlen(argv[i]);
		if(p+n+1 >= buf+sizeof buf)
			break;
		memmove(p, argv[i], n);
		p += n;
		*p++ = ' ';
	}
	p[-1] = 0;
	return buf;
}

int
nrunes(char *s, int nb)
{
	int i, n;
	Rune r;

	n = 0;
	for(i=0; i<nb; n++)
		i += chartorune(&r, s+i);
	return n;
}

void
stdinproc(void *v)
{
	int fd0 = rcfd;
	Event e;
	int n;

	USED(v);

	memset(&e, 0, sizeof e);
	for(;;){
		if(debug)
			fprint(2, "typing[%d,%d)\n", q.p, q.p+ntyper);
		if(winreadevent(win, &e) <= 0)
			error(nil);
		if(debug)
			fprint(2, "msg %c%c q[%d,%d)... ", e.c1, e.c2, e.q0, e.q1);
		qlock(&q.lk);
		switch(e.c1){
		default:
		Unknown:
			print("unknown message %c%c\n", e.c1, e.c2);
			break;

		case 'E':	/* write to body or tag; can't affect us */
			switch(e.c2){
			case 'I':
			case 'D':		/* body */
				if(debug)
					fprint(2, "shift typing %d... ", e.q1-e.q0);
				q.p += e.q1-e.q0;
				break;

			case 'i':
			case 'd':		/* tag */
				break;

			default:
				goto Unknown;
			}
			break;

		case 'F':	/* generated by our actions; ignore */
			break;

		case 'K':
		case 'M':
			switch(e.c2){
			case 'I':
				if(e.nr == 1 && e.text[0] == 0x7F) {
					char buf[1];
					winaddr(win, "#%ud,#%ud", e.q0, e.q1);
					winwrite(win, "data", "", 0);
					buf[0] = 0x7F;
					write(fd0, buf, 1);
					break;
				}
				if(e.q0 < q.p){
					if(debug)
						fprint(2, "shift typing %d... ", e.q1-e.q0);
					q.p += e.q1-e.q0;
				}
				else if(e.q0 <= q.p+ntyper){
					if(debug)
						fprint(2, "type... ");
					type(&e, fd0);
				}
				break;

			case 'D':
				n = delete(&e);
				q.p -= n;
				if(israw(fd0) && e.q1 >= q.p+n)
					sendbs(fd0, n);
				break;

			case 'x':
			case 'X':
				if(e.flag&1 || (e.c2=='x' && e.nr==0 && (!(e.flag&2) || win->e2.nr==0))){
					/* send it straight back */
					e.q0 = e.oq0;
					e.q1 = e.oq1;
					winwriteevent(win, &e);
					break;
				}
				char buf[100];
				snprint(buf, sizeof buf, "%s", e.text);
				if(cistrcmp(buf, "cook") == 0) {
					cook = 1;
					break;
				}
				if(cistrcmp(buf, "nocook") == 0) {
					cook = 0;
					break;
				}
				if(issend(&e)){
					sendcmd(&e, fd0);
					break;
				}
				if(e.flag & 8){
					if(e.q1 != e.q0){
						sende(&e, fd0, 0);
						sende(&blank, fd0, 0);
					}
					sende(&win->e3, fd0, 1);
				}else	 if(e.q1 != e.q0)
					sende(&e, fd0, 1);
				break;

			case 'l':
			case 'L':
				/* just send it back */
				e.q0 = e.oq0;
				e.q1 = e.oq1;
				winwriteevent(win, &e);
				break;

			case 'd':
			case 'i':
				break;

			default:
				goto Unknown;
			}
		}
		qunlock(&q.lk);
	}
}

int
dropcr(char *p, int n)
{
	int i;
	char *w, *r, *q;

	r = p;
	w = p;
	for(i=0; i<n; i++) {
		switch(*r) {
		case '\b':
			if(w > p)
				w--;
			break;
		case '\r':
			while(i<n-1 && *(r+1) == '\r') {
				r++;
				i++;
			}
			if(i<n && *(r+1) != '\n') {
				q = r;
				while(q>p && *(q-1) != '\n')
					q--;
				if(q > p) {
					w = q;
					break;
				}
			}
			*w++ = '\n';
			break;
		default:
			*w++ = *r;
			break;
		}
		r++;
	}
	return w-p;
}

void
stdoutproc(void *v)
{
	int fd1 = rcfd;
	int n, m, w, npart;
	char *buf, *s, *t;
	Rune r;
	char x[16], hold[UTFmax];

	USED(v);
	buf = malloc(8192+UTFmax+1);
	npart = 0;
	for(;;){
		/* Let typing have a go -- maybe there's a rubout waiting. */
		yield();
		outbusy = 0;
		n = read(fd1, buf+npart, 8192);
		outbusy = 1;
		outcount++;
		if(n <= 0)
			error(nil);

		n = echocancel(buf+npart, n);
		if(n == 0)
			continue;

		n = dropcrnl(buf+npart, n);
		if(n == 0)
			continue;

		n = dropcr(buf+npart, n);
		if(n == 0)
			continue;

		/* squash NULs */
		s = memchr(buf+npart, 0, n);
		if(s){
			for(t=s; s<buf+npart+n; s++)
				if(*t = *s)	/* assign = */
					t++;
			n = t-(buf+npart);
		}

		n += npart;

		/* hold on to final partial rune */
		npart = 0;
		while(n>0 && (buf[n-1]&0xC0)){
			--n;
			npart++;
			if((buf[n]&0xC0)!=0x80){
				if(fullrune(buf+n, npart)){
					w = chartorune(&r, buf+n);
					n += w;
					npart -= w;
				}
				break;
			}
		}
		if(n > 0){
			memmove(hold, buf+n, npart);
			buf[n] = 0;
			n = label(buf, n);
			buf[n] = 0;

			// clumsy but effective: notice password
			// prompts so we can disable echo.
			password = 0;
			if(cistrstr(buf, "password") || cistrstr(buf, "passphrase")) {
				int i;

				i = n;
				while(i > 0 && buf[i-1] == ' ')
					i--;
				password = i > 0 && buf[i-1] == ':';
			}

			qlock(&q.lk);
			m = sprint(x, "#%d", q.p);
			if(winaddr(win, "%s", x) != m){
				fprint(2, "stdout writing address %s: %r; resetting\n", x);
				if(winaddr(win, "$") < 0)
					fprint(2, "reset: %r\n");
				m = winreadaddr(win, nil);
				if(m >= 0)
					q.p = m;
			}
			if(winwrite(win, "data", buf, n) != n)
				error("stdout writing body");
			/* Make sure acme scrolls to the end of the above write. */
			if(winwrite(win, "data", nil, 0) != 0)
				error("stdout flushing body");
			q.p += nrunes(buf, n);
			qunlock(&q.lk);
			memmove(buf, hold, npart);
		}
	}
}

char wdir[512];
int
label(char *sr, int n)
{
	char *sl, *el, *er, *r, *p;

	er = sr+n;
	for(r=er-1; r>=sr; r--)
		if(*r == '\007')
			break;
	if(r < sr)
		return n;

	el = r+1;
	if(el-sr > sizeof wdir - strlen(name) - 20)
		sr = el - (sizeof wdir - strlen(name) - 20);
	for(sl=el-3; sl>=sr; sl--)
		if(sl[0]=='\033' && sl[1]==']' && sl[2]==';')
			break;
	if(sl < sr)
		return n;

	*r = 0;
	if(strcmp(sl+3, "*9term-hold+") != 0) {
		/*
		 * add /-sysname if not present
		 */
		snprint(wdir, sizeof wdir, "name %s", sl+3);
		p = strrchr(wdir, '/');
		if(p==nil || *(p+1) != '-'){
			p = wdir+strlen(wdir);
			if(*(p-1) != '/')
				*p++ = '/';
			*p++ = '-';
			strcpy(p, name);
		}
		winctl(win, "%s\n", wdir);
		*(strrchr(wdir, '/')+1) = 0;
		winctl(win, "dumpdir %s\n", wdir+5);
	}

	memmove(sl, el, er-el);
	n -= (el-sl);
	return n;
}

int
delete(Event *e)
{
	uint q0, q1;
	int deltap;

	q0 = e->q0;
	q1 = e->q1;
	if(q1 <= q.p)
		return e->q1-e->q0;
	if(q0 >= q.p+ntyper)
		return 0;
	deltap = 0;
	if(q0 < q.p){
		deltap = q.p-q0;
		q0 = 0;
	}else
		q0 -= q.p;
	if(q1 > q.p+ntyper)
		q1 = ntyper;
	else
		q1 -= q.p;
	deltype(q0, q1);
	return deltap;
}

void
addtype(int c, uint p0, char *b, int nb, int nr)
{
	int i, w;
	Rune r;
	uint p;
	char *b0;

	for(i=0; i<nb; i+=w){
		w = chartorune(&r, b+i);
		if((r==0x7F||r==3) && c=='K'){
			write(rcfd, "\x7F", 1);
			/* toss all typing */
			q.p += ntyper+nr;
			ntypebreak = 0;
			ntypeb = 0;
			ntyper = 0;
			/* buglet:  more than one delete ignored */
			return;
		}
		if(r=='\n' || r==0x04)
			ntypebreak++;
	}
	typing = realloc(typing, ntypeb+nb);
	if(typing == nil)
		error("realloc");
	if(p0 == ntyper)
		memmove(typing+ntypeb, b, nb);
	else{
		b0 = typing;
		for(p=0; p<p0 && b0<typing+ntypeb; p++){
			w = chartorune(&r, b0+i);
			b0 += w;
		}
		if(p != p0)
			error("typing: findrune");
		memmove(b0+nb, b0, (typing+ntypeb)-b0);
		memmove(b0, b, nb);
	}
	ntypeb += nb;
	ntyper += nr;
}

int
israw(int fd0)
{
	return (!cook || password) && !isecho(fd0);
}

void
sendtype(int fd0)
{
	int i, n, nr, raw;

	raw = israw(fd0);
	while(ntypebreak || (raw && ntypeb > 0)){
		for(i=0; i<ntypeb; i++)
			if(typing[i]=='\n' || typing[i]==0x04 || (i==ntypeb-1 && raw)){
				if((typing[i] == '\n' || typing[i] == 0x04) && ntypebreak > 0)
					ntypebreak--;
				n = i+1;
				i++;
				if(!raw)
					echoed(typing, n);
				if(write(fd0, typing, n) != n)
					error("sending to program");
				nr = nrunes(typing, i);
				q.p += nr;
				ntyper -= nr;
				ntypeb -= i;
				memmove(typing, typing+i, ntypeb);
				goto cont2;
			}
		print("no breakchar\n");
		ntypebreak = 0;
cont2:;
	}
}

void
sendbs(int fd0, int n)
{
	char buf[128];
	int m;

	memset(buf, 0x08, sizeof buf);
	while(n > 0) {
		m = sizeof buf;
		if(m > n)
			m = n;
		n -= m;
		write(fd0, buf, m);
	}
}

void
deltype(uint p0, uint p1)
{
	int w;
	uint p, b0, b1;
	Rune r;

	/* advance to p0 */
	b0 = 0;
	for(p=0; p<p0 && b0<ntypeb; p++){
		w = chartorune(&r, typing+b0);
		b0 += w;
	}
	if(p != p0)
		error("deltype 1");
	/* advance to p1 */
	b1 = b0;
	for(; p<p1 && b1<ntypeb; p++){
		w = chartorune(&r, typing+b1);
		b1 += w;
		if(r=='\n' || r==0x04)
			ntypebreak--;
	}
	if(p != p1)
		error("deltype 2");
	memmove(typing+b0, typing+b1, ntypeb-b1);
	ntypeb -= b1-b0;
	ntyper -= p1-p0;
}

void
type(Event *e, int fd0)
{
	int m, n, nr;
	char buf[128];

	if(e->nr > 0)
		addtype(e->c1, e->q0-q.p, e->text, e->nb, e->nr);
	else{
		m = e->q0;
		while(m < e->q1){
			winaddr(win, "#%d", m);
			n = winread(win, "data", buf, sizeof buf);
			nr = nrunes(buf, n);
			while(m+nr > e->q1){
				do; while(n>0 && (buf[--n]&0xC0)==0x80);
				--nr;
			}
			if(n == 0)
				break;
			addtype(e->c1, m-q.p, buf, n, nr);
			m += nr;
		}
	}
	if(israw(fd0)) {
		winaddr(win, "#%d,#%d", e->q0, e->q1);
		winwrite(win, "data", "", 0);
		q.p -= e->q1 - e->q0;
	}
	sendtype(fd0);
	if(e->nb > 0 && e->text[e->nb-1] == '\n')
		cook = 1;
}

void
sende(Event *e, int fd0, int donl)
{
	int m, n, nr, lastc, end;
	char buf[128];

	end = q.p+ntyper;
	winaddr(win, "#%d", end);
	if(e->nr > 0){
		winwrite(win, "data", e->text, e->nb);
		addtype(e->c1, ntyper, e->text, e->nb, e->nr);
		lastc = e->text[e->nb-1];
	}else{
		m = e->q0;
		lastc = 0;
		while(m < e->q1){
			winaddr(win, "#%d", m);
			n = winread(win, "data", buf, sizeof buf);
			nr = nrunes(buf, n);
			while(m+nr > e->q1){
				do; while(n>0 && (buf[--n]&0xC0)==0x80);
				--nr;
			}
			if(n == 0)
				break;
			winaddr(win, "#%d", end);
			winwrite(win, "data", buf, n);
			addtype(e->c1, ntyper, buf, n, nr);
			lastc = buf[n-1];
			m += nr;
			end += nr;
		}
	}
	if(donl && lastc!='\n'){
		winwrite(win, "data", "\n", 1);
		addtype(e->c1, ntyper, "\n", 1, 1);
	}
	winctl(win, "dot=addr");
	sendtype(fd0);
}

int
issend(Event *e)
{
	return e->nb >= 4 && strncmp(e->text, "Send", 4) == 0
		&& (e->nb == 4 || e->text[4] == ' ' || e->text[4] == '\t');
}

void
sendcmd(Event *e, int fd0)
{
	char *p;
	int n;
	uint q1;
	Event sel;

	if(e->flag & 8){
		sendtext(e->arg, strlen(e->arg), fd0, 1);
		return;
	}
	p = e->text+4;
	while(*p == ' ' || *p == '\t')
		p++;
	if(*p){
		sendtext(p, strlen(p), fd0, 1);
		return;
	}
	winctl(win, "addr=dot");
	n = winreadaddr(win, &q1);
	if(n < 0)
		return;
	memset(&sel, 0, sizeof sel);
	sel.c1 = 'M';
	sel.q0 = n;
	sel.q1 = q1;
	sende(&sel, fd0, 1);
}

void
sendtext(char *s, int n, int fd0, int donl)
{
	int raw, nr;

	raw = israw(fd0);
	nr = nrunes(s, n);
	if(!raw){
		winaddr(win, "#%d", q.p+ntyper);
		if(n > 0)
			winwrite(win, "data", s, n);
	}
	if(n > 0)
		addtype('M', ntyper, s, n, nr);
	if(donl && (n == 0 || s[n-1] != '\n')){
		if(!raw)
			winwrite(win, "data", "\n", 1);
		addtype('M', ntyper, "\n", 1, 1);
		nr++;
	}
	if(raw)
		q.p -= nr;	/* not echoed, so it never reaches the body */
	else{
		winwrite(win, "data", nil, 0);	/* scroll to the end */
		winctl(win, "dot=addr");
	}
	sendtype(fd0);
	cook = 1;
}
